owner: evandempsey
repo: coursepropeller.github.io

# Add your sites here
sites:
  - name: Homepage
    url: https://coursepropeller.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Test for HEAD
    method: HEAD
    url: https://www.google.com
  - name: Secret Site
    url: $SECRET_SITE

assignees:
  - evandempsey

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.coursepropeller.com
  logoUrl: https://raw.githubusercontent.com/CoursePropeller/coursepropeller.github.io/master/assets/logo_text_black.svg
  name: CoursePropeller Status
  introTitle: CoursePropeller Status
  introMessage: Details of service status and incidents.
  navbar:
    - title: Home
      href: https://coursepropeller.com
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/CoursePropeller/coursepropeller.github.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
