owner: CoursePropeller
repo: coursepropeller.github.io
user-agent: evandempsey
sites:
  - name: Homepage
    url: https://coursepropeller.com

assignees:
  - evandempsey

status-website:
  cname: status.coursepropeller.com
  logoUrl: https://status.coursepropeller.com/logo_text_black.svg
  name: ''
  introTitle: System Status
  introMessage: Component uptime and incidents.
  navbar:
    - title: Home
      href: https://coursepropeller.com
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/CoursePropeller/coursepropeller.github.io

  favicon: https://status.coursepropeller.com/favicon-32x32.png
  themeUrl: https://status.coursepropeller.com/coursepropeller_theme.css

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
