owner: CoursePropeller
repo: coursepropeller.github.io
user-agent: evandempsey
sites:
  - name: Homepage
    url: https://coursepropeller.com

assignees:
  - evandempsey

status-website:
  cname: status.coursepropeller.com
  logoUrl: https://raw.githubusercontent.com/CoursePropeller/coursepropeller.github.io/master/assets/logo_text_black.svg
  name: 'CoursePropeller System Status'
  introTitle: System Status
  introMessage: Component uptime and incidents.
  navbar:
    - title: Home
      href: https://coursepropeller.com
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/CoursePropeller/coursepropeller.github.io

  favicon: https://raw.githubusercontent.com/CoursePropeller/coursepropeller.github.io/master/assets/favicon-32x32.png
  css: ":root {
    --body-background-color: #f5f6fe;
    --nav-current-border-bottom-color: #3252c3;
    --body-text-color: #404040;

    --submit-button-border-color: #3252c3;
    --submit-button-background-color: #3252c3;
    --submit-button-color: #ffffff;

    --error-button-border-color: #3252c3;
    --error-button-background-color: #3252c3;
    --error-button-color: #ffffff;
  }
  .logo > div {
    display: none;
  }"

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
